-- External variable database definition for H2 
-- Generated 5/28/15 4:32 PM
-- Descriptor: metrics/metrics.xvar (currently edited)
-- External variable SalesOrder
DROP TABLE IF EXISTS SalesOrder;
CREATE TABLE SalesOrder (SALESORDERREF VARCHAR(250), CLIENTID INTEGER, CLIENTNAME VARCHAR(250), SALESDATE VARCHAR(250), TOTALAMOUNT NUMERIC, SALESREP VARCHAR(250), REVIEWMANAGER VARCHAR(250), STATUS VARCHAR(250), RECIEVEDDATE TIMESTAMP, REVIEWEDDATE TIMESTAMP, APPROVEDDATE TIMESTAMP, REJECTEDDATE TIMESTAMP, ELECTRONICSPROVISIONEDDATE TIMESTAMP, OFFICEPROVISIONEDDATE TIMESTAMP, DELIVEREDDATE TIMESTAMP, ITEMSCOUNT INTEGER, OFFICECOUNT INTEGER, ELECTRONICSCOUNT INTEGER, DISCOUNT FLOAT);
CREATE INDEX SalesOrder_KEYS ON SalesOrder (SALESORDERREF);
-- External variable SalesItem
DROP TABLE IF EXISTS SalesItem;
CREATE TABLE SalesItem (ITEMREF VARCHAR(250), SALESORDERREF VARCHAR(250), PRODUCTNAME VARCHAR(250), PRODUCTFAMILY VARCHAR(250), QUANTITY INTEGER, PRICE FLOAT);
CREATE INDEX SalesItem_KEYS ON SalesItem (ITEMREF, SALESORDERREF);

